import { db } from './index.js';
import { regulations, complianceChecklist, regulatorySources, regulatoryUpdates } from './schema.js';

export async function seedComplianceData() {
  console.log('Seeding compliance data...');

  // Clear existing
  await db.delete(regulatoryUpdates);
  await db.delete(complianceChecklist);
  await db.delete(regulations);
  await db.delete(regulatorySources);

  // ===== REGULATIONS =====
  const regs = await db.insert(regulations).values([
    // === POLICY ===
    {
      title: 'Intelligent Robot Development and Distribution Promotion Act (지능형로봇법)',
      titleKo: '지능형 로봇 개발 및 보급 촉진법',
      category: 'policy',
      region: 'korea',
      status: 'active',
      effectiveDate: '2008-09-22',
      lastAmendedDate: '2023-05-16',
      summary: 'Defines intelligent robots as machines that autonomously perceive and act. Government establishes 5-year basic plans and reviews policies through Robot Industry Policy Council.',
      summaryKo: '외부환경을 스스로 인식하고 상황을 판단하여 자율적으로 동작하는 기계장치를 지능형 로봇으로 정의. 정부는 5년마다 기본계획을 수립하고 로봇산업정책심의회를 통해 정책을 심의.',
      lgImpact: 'critical',
      lgImpactAnalysis: 'CLOiD/KAPEX가 이 법의 적용 대상에 해당하는지 분류 검토 필요. 실외이동로봇 운행안전인증 제도 적용 여부도 확인 필수.',
      sourceUrl: 'https://www.law.go.kr/법령/지능형로봇법',
      sourceName: '국가법령정보센터',
      tags: ['로봇법', '기본법', '안전인증', '실외이동로봇'],
    },
    {
      title: 'Humanoid ROBOT Act (S.3275)',
      titleKo: '휴머노이드 로봇 법안 (S.3275)',
      category: 'policy',
      region: 'us',
      status: 'proposed',
      effectiveDate: '2025-01-01',
      summary: 'Prohibits US federal agencies from procuring humanoids designed/manufactured by "covered entities" (China, etc.). Expands CFIUS review to humanoid tech investments.',
      summaryKo: '미 연방정부 기관이 중국 등 우려 국가가 설계·제조한 휴머노이드를 조달하거나 계약에서 사용하는 것을 금지. CFIUS가 휴머노이드 기술 투자를 심사하도록 확대.',
      lgImpact: 'high',
      lgImpactAnalysis: 'LG가 미국 시장 진입 시 공급망 원산지 증명이 핵심 이슈. 부품의 중국산 비율 관리 필요.',
      sourceUrl: 'https://www.congress.gov/bill/118th-congress/senate-bill/3275',
      sourceName: 'Congress.gov',
      tags: ['supply-chain', 'CFIUS', 'procurement-ban'],
    },
    {
      title: 'EU Artificial Intelligence Act',
      titleKo: 'EU 인공지능법',
      category: 'policy',
      region: 'eu',
      status: 'active',
      effectiveDate: '2024-08-01',
      summary: 'Phased implementation: prohibited AI practices enforced from Feb 2025, high-risk AI obligations from Aug 2026/2027. Humanoid robots likely classified as high-risk under Machinery Regulation safety component.',
      summaryKo: '2024년 8월 발효 후 단계 적용. 고위험 AI 규정은 2026년 8월 및 2027년 8월에 시행. 휴머노이드의 기계지침 적용 시 safety component로서 고위험 해당 가능성 높음.',
      lgImpact: 'critical',
      lgImpactAnalysis: '고위험 분류 해당 여부 판단 필수. 위반 시 최대 3,500만 유로 또는 글로벌 매출 7% 제재. 준수 로드맵 수립 시급.',
      sourceUrl: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
      sourceName: 'EUR-Lex',
      tags: ['AI-Act', 'high-risk', 'machinery-regulation'],
    },
    {
      title: 'MIIT Humanoid Standard Framework (2026 Edition)',
      titleKo: 'MIIT 휴머노이드 표준체계 (2026년판)',
      category: 'policy',
      region: 'china',
      status: 'active',
      effectiveDate: '2026-01-01',
      summary: '6-pillar national standard framework for humanoids. HEIS committee (120+ researchers/industry/policymakers) develops standards.',
      summaryKo: '6개 기둥으로 구성된 국가 표준 프레임워크. MIIT 산하 HEIS 위원회(120명 이상)가 개발.',
      lgImpact: 'high',
      lgImpactAnalysis: '중국 시장 진출 시 해당 표준 프레임워크와의 호환성/차별화 전략 필요.',
      sourceUrl: 'https://www.miit.gov.cn',
      sourceName: 'MIIT',
      tags: ['national-standard', 'HEIS', '6-pillar'],
    },
    // === SAFETY ===
    {
      title: 'ISO 10218:2025 — Industrial Robots Safety',
      titleKo: 'ISO 10218:2025 — 산업용 로봇 안전',
      category: 'safety',
      region: 'international',
      status: 'active',
      effectiveDate: '2025-01-01',
      summary: 'Adopted as ANSI/A3 R15.06-2025 in the US. Strengthened functional safety requirements and added cybersecurity considerations. Expanded from 162 to 374 pages.',
      summaryKo: 'ANSI/A3 R15.06-2025로 미국 채택. 기능안전 요건 강화, 사이버보안 고려사항 추가. 162페이지에서 374페이지로 대폭 확대.',
      lgImpact: 'critical',
      lgImpactAnalysis: '산업용 휴머노이드 배치 시 1차 적용 대상. 적합성 평가 계획 수립 필요.',
      sourceName: 'ISO',
      tags: ['ISO', 'functional-safety', 'cybersecurity'],
    },
    {
      title: 'ISO 13482 — Personal Care Robot Safety',
      titleKo: 'ISO 13482 — 생활지원로봇 안전',
      category: 'safety',
      region: 'international',
      status: 'active',
      summary: 'Safety standards for personal care robots. Updated in 2025 but predates modern AI capabilities (foundation models).',
      summaryKo: '생활지원로봇 안전 규격. 2025년 업데이트되었으나 현대 AI 역량(파운데이션 모델 등)을 반영하기 이전에 제정된 한계.',
      lgImpact: 'high',
      lgImpactAnalysis: '가정용/서비스용 휴머노이드 적용 시 참조 필요.',
      sourceName: 'ISO',
      tags: ['ISO', 'personal-care', 'service-robot'],
    },
    {
      title: 'ISO 25785-1 — Bipedal Humanoid Robot Safety (In Development)',
      titleKo: 'ISO 25785-1 — 이족보행 휴머노이드 안전 (개발 중)',
      category: 'safety',
      region: 'international',
      status: 'draft',
      summary: 'Focuses on active stability control and fall risk management for bipedal systems. Complements ISO 10218 and ISO 13482.',
      summaryKo: '이족보행 시스템의 능동 안정성 제어 및 넘어짐 위험 관리에 초점. ISO 10218, ISO 13482를 보완하는 위치.',
      lgImpact: 'critical',
      lgImpactAnalysis: '휴머노이드 전용 최초 국제 안전 표준. 표준 제정 참여를 통한 선도적 포지션 확보 기회.',
      sourceName: 'ISO',
      tags: ['ISO', 'bipedal', 'fall-risk', 'stability'],
    },
    {
      title: 'IEC 62443 — Industrial Cybersecurity',
      titleKo: 'IEC 62443 — 산업 사이버보안',
      category: 'safety',
      region: 'international',
      status: 'active',
      summary: 'Cybersecurity standards for network-connected robots and industrial control systems.',
      summaryKo: '네트워크 연결 로봇의 사이버보안 표준.',
      lgImpact: 'high',
      lgImpactAnalysis: '네트워크 연결 휴머노이드의 사이버보안 적용 범위 정의 필요.',
      sourceName: 'IEC',
      tags: ['cybersecurity', 'IEC', 'network-security'],
    },
    // === LEGAL ===
    {
      title: 'Product Liability Act (제조물 책임법)',
      titleKo: '제조물 책임법',
      category: 'legal',
      region: 'korea',
      status: 'active',
      summary: 'Liability allocation between manufacturer, system integrator, operator, and AI model developer remains ambiguous for humanoid accidents.',
      summaryKo: '휴머노이드가 작업 중 사고 발생 시 제조사·시스템 통합사·운영사·AI 모델 개발사 간 책임 배분이 불명확.',
      lgImpact: 'critical',
      lgImpactAnalysis: '사고 시 책임 귀속 구조 정의 (제조사 vs SI vs 운영사 vs AI 개발사) 필요.',
      sourceName: '국가법령정보센터',
      tags: ['product-liability', 'responsibility-allocation'],
    },
    {
      title: 'Mandatory Liability Insurance for Outdoor Mobile Robots',
      titleKo: '실외이동로봇 책임보험 의무',
      category: 'legal',
      region: 'korea',
      status: 'active',
      effectiveDate: '2023-05-16',
      summary: 'Operators of safety-certified outdoor mobile robots must carry mandatory liability insurance for personal and property damage.',
      summaryKo: '안전인증을 받은 실외이동로봇 운영 사업자는 인적·물적 손해 배상을 위한 책임보험 가입이 의무화.',
      lgImpact: 'high',
      lgImpactAnalysis: '실외 운용 시 책임보험 의무 가입 대상 해당 여부 확인 필요.',
      sourceName: '국가법령정보센터',
      tags: ['liability-insurance', 'outdoor-robot'],
    },
    {
      title: 'EU Product Liability Directive (PLD) Revision',
      titleKo: 'EU 제조물 책임 지침 (PLD) 개정안',
      category: 'legal',
      region: 'eu',
      status: 'proposed',
      summary: 'Revision to include AI systems in product liability framework. Shifts burden of proof and expands defective product definition.',
      summaryKo: 'AI 시스템을 제조물 책임 프레임워크에 포함하는 개정안. 입증 책임 전환 및 결함 제품 정의 확대.',
      lgImpact: 'high',
      lgImpactAnalysis: 'EU 시장 진출 시 AI 시스템 포함 제조물 책임 대응 전략 필요.',
      tags: ['PLD', 'AI-liability', 'burden-of-proof'],
    },
    // === PRIVACY ===
    {
      title: 'GDPR — General Data Protection Regulation',
      titleKo: 'GDPR — 일반 데이터 보호 규정',
      category: 'privacy',
      region: 'eu',
      status: 'active',
      effectiveDate: '2018-05-25',
      summary: 'Legal basis for personal data processing, data minimization, purpose limitation, data subject rights. Humanoid robot cameras/microphones/sensors are data collection devices under GDPR.',
      summaryKo: '개인정보 처리의 법적 근거, 최소 수집, 목적 제한, 데이터 주체 권리 보장. 휴머노이드 카메라/마이크/센서는 GDPR상 데이터 수집 장치에 해당.',
      lgImpact: 'critical',
      lgImpactAnalysis: 'Privacy by Design을 LG 경쟁 차별화 요소로 포지셔닝 가능. Unitree G1 데이터 유출 사건은 경쟁사 약점이자 LG의 기회.',
      sourceName: 'EUR-Lex',
      tags: ['GDPR', 'privacy-by-design', 'data-minimization'],
    },
    {
      title: 'Personal Information Protection Act (개인정보보호법)',
      titleKo: '개인정보보호법',
      category: 'privacy',
      region: 'korea',
      status: 'active',
      summary: 'Regulations on video information processing devices, consent requirements for in-home data collection by robots.',
      summaryKo: '영상정보처리기기 운영 관련 규정, 가정 내 수집 시 동의 요건.',
      lgImpact: 'critical',
      lgImpactAnalysis: '수집 데이터 유형 목록화 및 On-device vs Cloud 처리 아키텍처 결정 필요.',
      sourceName: '국가법령정보센터',
      tags: ['privacy', 'video-processing', 'consent'],
    },
    {
      title: 'Unitree G1 Data Leak Incident — Privacy Precedent',
      titleKo: 'Unitree G1 데이터 유출 사건 — 프라이버시 선례',
      category: 'privacy',
      region: 'international',
      status: 'active',
      summary: 'Unitree G1 found secretly transmitting audio, video, sensor data to Chinese servers every 5 minutes. Violates GDPR Art.6 & Art.13, CCPA.',
      summaryKo: 'Unitree G1이 5분마다 오디오, 비디오, 센서 데이터를 중국 서버로 비밀리에 전송한 것이 발견됨. GDPR 제6조 및 제13조, CCPA 위반.',
      lgImpact: 'high',
      lgImpactAnalysis: '경쟁사 약점이자 LG의 차별화 포인트. Privacy by Design 기조로 선제적 포지셔닝 가능.',
      tags: ['Unitree', 'data-leak', 'competitive-opportunity'],
    },
  ]).returning();

  // ===== CHECKLIST =====
  const checklistItems = [
    // Policy
    { category: 'policy', region: 'korea', title: 'CLOiD/KAPEX 타겟 시장별 규제 분류 (산업용 vs 서비스용 vs 가정용)', priority: 'critical', sortOrder: 1 },
    { category: 'policy', region: 'korea', title: '규제 샌드박스 활용 계획 수립', priority: 'high', sortOrder: 2 },
    { category: 'policy', region: 'us', title: '미국 ROBOT Act 공급망 원산지 리스크 평가', priority: 'critical', sortOrder: 3 },
    { category: 'policy', region: 'eu', title: 'EU AI Act 고위험 분류 해당 여부 및 준수 로드맵', priority: 'critical', sortOrder: 4 },
    { category: 'policy', region: 'china', title: '중국 표준체계와의 호환성/차별화 전략', priority: 'high', sortOrder: 5 },
    { category: 'policy', region: 'international', title: '수출 통제(미중 기술갈등) 하 부품 조달 리스크 평가', priority: 'high', sortOrder: 6 },
    // Safety
    { category: 'safety', region: 'international', title: 'ISO 10218(2025) / ISO 13482 적합성 평가 계획', priority: 'critical', sortOrder: 10 },
    { category: 'safety', region: 'international', title: 'ISO 25785-1 동향 모니터링 및 표준 제정 참여', priority: 'high', sortOrder: 11 },
    { category: 'safety', region: 'international', title: '낙상·충돌·협착 등 물리적 위험 시나리오 도출 및 위험성 평가', priority: 'critical', sortOrder: 12 },
    { category: 'safety', region: 'international', title: '비상정지(E-stop) 메커니즘 설계 기준', priority: 'critical', sortOrder: 13 },
    { category: 'safety', region: 'international', title: '힘/토크 제한, 접촉력 허용 범위 설정', priority: 'high', sortOrder: 14 },
    { category: 'safety', region: 'international', title: '사이버보안 (IEC 62443) 적용 범위 정의', priority: 'high', sortOrder: 15 },
    { category: 'safety', region: 'international', title: '기능안전 (SIL/PL 등급) 목표 설정', priority: 'high', sortOrder: 16 },
    { category: 'safety', region: 'international', title: '의인화에 따른 심리적 안전 가이드라인', priority: 'medium', sortOrder: 17 },
    { category: 'safety', region: 'international', title: 'NRTL(미국)/CE(EU)/KC(한국) 인증 경로 매핑', priority: 'high', sortOrder: 18 },
    // Legal
    { category: 'legal', region: 'korea', title: '사고 시 책임 귀속 구조 정의 (제조사 vs SI vs 운영사 vs AI 개발사)', priority: 'critical', sortOrder: 20 },
    { category: 'legal', region: 'korea', title: '제조물 책임법 적용 범위 및 면책 요건 검토', priority: 'critical', sortOrder: 21 },
    { category: 'legal', region: 'korea', title: '책임보험 의무 가입 대상 해당 여부 (실외이동 시)', priority: 'high', sortOrder: 22 },
    { category: 'legal', region: 'korea', title: '산업안전보건법상 휴머노이드 분류 및 안전조치 기준', priority: 'high', sortOrder: 23 },
    { category: 'legal', region: 'international', title: '로봇이 생성/수집하는 데이터의 소유권·라이선싱 계약 구조', priority: 'high', sortOrder: 24 },
    { category: 'legal', region: 'eu', title: 'EU 제조물 책임 지침(PLD) 개정안 대응', priority: 'high', sortOrder: 25 },
    { category: 'legal', region: 'international', title: '고용 영향 평가 및 로봇세 관련 논의 모니터링', priority: 'medium', sortOrder: 26 },
    { category: 'legal', region: 'international', title: '각 시장별 소송/분쟁 리스크 시나리오 사전 검토', priority: 'high', sortOrder: 27 },
    // Privacy
    { category: 'privacy', region: 'international', title: '수집 데이터 유형 목록화 (RGB, Depth, 오디오, LiDAR, IMU, 터치 등)', priority: 'critical', sortOrder: 30 },
    { category: 'privacy', region: 'eu', title: '데이터 처리 목적 및 법적 근거 정의 (GDPR Art.6 기준)', priority: 'critical', sortOrder: 31 },
    { category: 'privacy', region: 'international', title: 'On-device vs Cloud 처리 아키텍처 결정', priority: 'critical', sortOrder: 32 },
    { category: 'privacy', region: 'international', title: '데이터 최소 수집 원칙 (Data Minimization) 설계', priority: 'high', sortOrder: 33 },
    { category: 'privacy', region: 'international', title: '다중 사용자 동의 메커니즘 (가정 내 가족, 방문객 등)', priority: 'high', sortOrder: 34 },
    { category: 'privacy', region: 'international', title: '원격 조종(Teleoperation) 시 데이터 접근 범위 및 고지', priority: 'high', sortOrder: 35 },
    { category: 'privacy', region: 'international', title: 'AI 모델 학습 데이터 사용 여부에 대한 Opt-in/Opt-out 정책', priority: 'high', sortOrder: 36 },
    { category: 'privacy', region: 'international', title: '데이터 보존 기간 및 삭제 정책', priority: 'high', sortOrder: 37 },
    { category: 'privacy', region: 'international', title: '국경 간 데이터 이전 (Cross-border transfer) 요건', priority: 'high', sortOrder: 38 },
    { category: 'privacy', region: 'international', title: '익명화/가명화 처리 기준', priority: 'medium', sortOrder: 39 },
    { category: 'privacy', region: 'international', title: '사이버보안 침해 시 데이터 유출 대응 계획', priority: 'high', sortOrder: 40 },
    { category: 'privacy', region: 'international', title: 'Privacy by Design을 LG의 경쟁 차별화 요소로 포지셔닝', priority: 'critical', sortOrder: 41 },
  ];

  await db.insert(complianceChecklist).values(checklistItems);

  // ===== REGULATORY SOURCES =====
  await db.insert(regulatorySources).values([
    { name: '국가법령정보센터', url: 'https://www.law.go.kr/RSS/lsRss.do', type: 'rss', region: 'korea', category: 'policy', schedule: 'daily' },
    { name: '규제정보포털', url: 'https://www.better.go.kr', type: 'webpage', region: 'korea', category: 'policy', schedule: 'daily' },
    { name: 'EUR-Lex AI Act', url: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj', type: 'webpage', region: 'eu', category: 'policy', schedule: 'weekly' },
    { name: 'Congress.gov Robot Bills', url: 'https://api.congress.gov/v3/bill', type: 'api', region: 'us', category: 'policy', schedule: 'daily' },
    { name: 'MIIT Announcements', url: 'https://www.miit.gov.cn', type: 'webpage', region: 'china', category: 'policy', schedule: 'weekly' },
    { name: 'ISO Standards Updates', url: 'https://www.iso.org/rss', type: 'rss', region: 'international', category: 'safety', schedule: 'weekly' },
    { name: 'IAPP Privacy News', url: 'https://iapp.org/rss', type: 'rss', region: 'international', category: 'privacy', schedule: 'daily' },
    { name: 'IRobot News Korea', url: 'https://www.irobotnews.com', type: 'webpage', region: 'korea', category: 'policy', schedule: 'daily' },
  ]);

  // ===== SAMPLE UPDATES =====
  await db.insert(regulatoryUpdates).values([
    {
      regulationId: regs[0]!.id, // 지능형로봇법
      title: 'Korea 2026 R&D Focus: Humanoid Safety Standards & Component Localization',
      titleKo: '2026년 한국 정부 R&D 방향: 휴머노이드 안전기준 마련과 핵심부품 국산화',
      updateType: 'guidance',
      category: 'policy',
      region: 'korea',
      summary: 'KEIT 박일우 로봇PD: R&D를 휴머노이드 안전기준 마련과 핵심부품 국산화에 집중. 2027년까지 표준화된 안전성 평가 데이터셋과 시험 방법 마련, 2028년 국가로봇테스트필드와 연계해 종합 검증 체계 완성 목표.',
      summaryKo: 'KEIT 박일우 로봇PD는 올해 R&D를 휴머노이드 안전기준 마련과 핵심부품 국산화에 집중한다고 밝힘. 2027년까지 표준화된 안전성 평가 데이터셋과 시험 방법을 마련하고, 2028년에는 국가로봇테스트필드와 연계해 종합 검증 체계를 완성할 목표.',
      lgImpact: 'high',
      lgActionRequired: '국가로봇테스트필드 사전 협의 및 안전기준 마련 참여',
      sourceName: 'IRobot News',
      publishedAt: new Date('2026-03-15'),
      detectedBy: 'manual',
    },
    {
      regulationId: regs[3]!.id, // MIIT
      title: 'China Releases World-First Humanoid Intelligence Rating Standard',
      titleKo: '중국, 세계 최초 휴머노이드 지능 등급 표준 발표',
      updateType: 'new_regulation',
      category: 'policy',
      region: 'china',
      summary: 'Beijing Humanoid Robot Innovation Center published T/CIE 298-2025: 4-dimension, 5-level framework with 22 primary indicators and 100+ technical provisions.',
      summaryKo: '베이징 휴머노이드 로봇 혁신센터가 세계 최초 휴머노이드 지능 등급 표준(T/CIE 298-2025) 발표. 4차원 5등급 프레임워크, 22개 1차 지표와 100개 이상 기술 조항 포함.',
      lgImpact: 'high',
      lgActionRequired: '지능 등급 표준 분석 및 CLOiD/KAPEX 매핑',
      publishedAt: new Date('2025-05-01'),
      detectedBy: 'manual',
    },
    {
      title: 'Unitree G1 Found Secretly Transmitting Data to Chinese Servers',
      titleKo: 'Unitree G1, 중국 서버로 비밀 데이터 전송 발각',
      updateType: 'enforcement',
      category: 'privacy',
      region: 'international',
      summary: 'Unitree G1 found transmitting audio, video, sensor data to Chinese servers every 5 minutes without user consent. Violates GDPR Art.6 & Art.13, CCPA.',
      summaryKo: 'Unitree G1이 5분마다 오디오, 비디오, 센서 데이터를 사용자 동의 없이 중국 서버로 전송. GDPR 제6조, 제13조, CCPA 위반.',
      lgImpact: 'high',
      lgActionRequired: 'Privacy by Design 차별화 전략 수립, 경쟁사 벤치마크 활용',
      publishedAt: new Date('2025-11-01'),
      detectedBy: 'manual',
    },
  ]);

  console.log(`Seeded ${regs.length} regulations, ${checklistItems.length} checklist items, 8 sources, 3 updates`);
}
