'use client';

import { AuthGuard } from '@/components/auth/AuthGuard';
import { PageHeader } from '@/components/layout/PageHeader';
import { EventCalendar } from '@/components/event-calendar/EventCalendar';
import type { RobotAIEvent } from '@/types/event-calendar';

const EVENTS: RobotAIEvent[] = [
  {
    id: '1',
    name: 'CES 2026',
    type: '전시',
    date_start: '2026-01-06',
    date_end: '2026-01-09',
    location: 'Las Vegas Convention Center',
    country: '미국',
    url: 'https://www.ces.tech',
    tags: ['소비자전자', '로봇', 'AI', '자율주행'],
    relevance_score: 5,
  },
  {
    id: '2',
    name: 'ICRA 2025',
    type: '학회',
    date_start: '2025-06-01',
    date_end: '2025-06-05',
    location: 'Georgia World Congress Center, Atlanta',
    country: '미국',
    url: 'https://2025.ieee-icra.org',
    tags: ['로보틱스', '자동화', 'IEEE', '논문발표'],
    relevance_score: 5,
  },
  {
    id: '3',
    name: 'EU AI Act 전면 시행',
    type: '정책',
    date_start: '2026-08-02',
    date_end: '2026-08-02',
    location: 'Brussels',
    country: '유럽(EU)',
    url: 'https://artificialintelligenceact.eu',
    tags: ['AI규제', '컴플라이언스', '고위험AI', 'CE마킹'],
    relevance_score: 5,
  },
  {
    id: '4',
    name: 'IREX 2025 (국제로봇전시회)',
    type: '전시',
    date_start: '2025-10-15',
    date_end: '2025-10-18',
    location: 'Tokyo Big Sight',
    country: '일본',
    url: 'https://irex.nikkan.co.jp',
    tags: ['산업로봇', '서비스로봇', '협동로봇', '일본'],
    relevance_score: 5,
  },
  {
    id: '5',
    name: 'IROS 2025',
    type: '학회',
    date_start: '2025-10-19',
    date_end: '2025-10-23',
    location: 'Hangzhou International Expo Center',
    country: '중국',
    url: 'https://iros2025.org',
    tags: ['지능시스템', 'IEEE', '로보틱스', '논문발표'],
    relevance_score: 4,
  },
  {
    id: '6',
    name: 'AWE 2026 (Augmented World Expo)',
    type: '전시',
    date_start: '2026-06-03',
    date_end: '2026-06-05',
    location: 'Santa Clara Convention Center',
    country: '미국',
    url: 'https://www.awexr.com',
    tags: ['XR', 'AR', '로봇인터페이스', '공간컴퓨팅'],
    relevance_score: 4,
  },
  {
    id: '7',
    name: 'CoRL 2025 (Conference on Robot Learning)',
    type: '학회',
    date_start: '2025-11-04',
    date_end: '2025-11-07',
    location: 'Seoul, COEX',
    country: '한국',
    url: 'https://www.corl2025.org',
    tags: ['로봇학습', '강화학습', '모방학습', 'AI'],
    relevance_score: 5,
  },
  {
    id: '8',
    name: '한국 로봇산업 진흥법 시행령 개정',
    type: '정책',
    date_start: '2025-07-01',
    date_end: '2025-07-01',
    location: 'Seoul',
    country: '한국',
    url: 'https://www.law.go.kr',
    tags: ['로봇진흥법', '규제개선', '안전기준', '한국정책'],
    relevance_score: 4,
  },
  {
    id: '9',
    name: 'RoboCup 2026',
    type: '학회',
    date_start: '2026-07-14',
    date_end: '2026-07-20',
    location: 'TBD, Europe',
    country: '유럽(EU)',
    url: 'https://www.robocup.org',
    tags: ['자율로봇', '축구로봇', '교육', '경진대회'],
    relevance_score: 3,
  },
  {
    id: '10',
    name: '2025 로보월드 (ROBOT WORLD)',
    type: '전시',
    date_start: '2025-10-29',
    date_end: '2025-11-01',
    location: 'KINTEX, Goyang',
    country: '한국',
    url: 'https://www.robotworld.or.kr',
    tags: ['산업로봇', '서비스로봇', '부품', '한국전시'],
    relevance_score: 4,
  },
  {
    id: '11',
    name: 'Automate 2026',
    type: '전시',
    date_start: '2026-05-18',
    date_end: '2026-05-21',
    location: 'Huntington Place, Detroit',
    country: '미국',
    url: 'https://www.automateshow.com',
    tags: ['자동화', '산업로봇', '비전', '모션제어'],
    relevance_score: 4,
  },
  {
    id: '12',
    name: 'RSS 2026 (Robotics: Science and Systems)',
    type: '학회',
    date_start: '2026-06-22',
    date_end: '2026-06-26',
    location: 'TBD, USA',
    country: '미국',
    url: 'https://roboticsconference.org',
    tags: ['로보틱스', '기초연구', '논문발표', '학술'],
    relevance_score: 4,
  },
  {
    id: '13',
    name: 'EU Machinery Regulation 전면 적용',
    type: '정책',
    date_start: '2027-01-14',
    date_end: '2027-01-14',
    location: 'Brussels',
    country: '유럽(EU)',
    url: 'https://ec.europa.eu',
    tags: ['기계규정', '안전인증', 'CE마킹', '산업로봇'],
    relevance_score: 5,
  },
  {
    id: '14',
    name: 'Hannover Messe 2026',
    type: '전시',
    date_start: '2026-04-20',
    date_end: '2026-04-24',
    location: 'Hannover Fairground',
    country: '독일',
    url: 'https://www.hannovermesse.de',
    tags: ['산업자동화', '디지털트윈', '로봇', '스마트팩토리'],
    relevance_score: 4,
  },
  {
    id: '15',
    name: 'HRI 2026 (Human-Robot Interaction)',
    type: '학회',
    date_start: '2026-03-09',
    date_end: '2026-03-12',
    location: 'Melbourne Convention Centre',
    country: '호주',
    url: 'https://humanrobotinteraction.org',
    tags: ['인간로봇상호작용', 'HRI', '사회로봇', 'UX'],
    relevance_score: 3,
  },
  {
    id: '16',
    name: '일본 로봇전략 2030 중간점검',
    type: '정책',
    date_start: '2025-09-01',
    date_end: '2025-09-01',
    location: 'Tokyo',
    country: '일본',
    url: 'https://www.meti.go.jp',
    tags: ['일본정책', '로봇전략', '산업정책', 'Society5.0'],
    relevance_score: 3,
  },
  {
    id: '17',
    name: 'ICRA 2026',
    type: '학회',
    date_start: '2026-05-19',
    date_end: '2026-05-23',
    location: 'TBD',
    country: '미국',
    url: 'https://ieee-icra.org',
    tags: ['로보틱스', '자동화', 'IEEE', '논문발표'],
    relevance_score: 5,
  },
  {
    id: '18',
    name: '한국 지능형로봇법 개정안 시행',
    type: '정책',
    date_start: '2026-03-01',
    date_end: '2026-03-01',
    location: 'Seoul',
    country: '한국',
    url: 'https://www.law.go.kr',
    tags: ['지능형로봇', '한국정책', '안전인증', '규제'],
    relevance_score: 4,
  },
  {
    id: '19',
    name: 'World Robot Summit 2025',
    type: '전시',
    date_start: '2025-08-21',
    date_end: '2025-08-23',
    location: 'Aichi Sky Expo',
    country: '일본',
    url: 'https://wrs.nedo.go.jp',
    tags: ['로봇경진대회', '서비스로봇', '재난로봇', '일본'],
    relevance_score: 3,
  },
  {
    id: '20',
    name: '미국 NIST AI 600-1 로봇 안전 프레임워크 발표',
    type: '정책',
    date_start: '2025-12-15',
    date_end: '2025-12-15',
    location: 'Washington D.C.',
    country: '미국',
    url: 'https://www.nist.gov',
    tags: ['NIST', 'AI안전', '로봇안전', '미국규제'],
    relevance_score: 4,
  },
];

function EventCalendarContent() {
  return (
    <div className="px-4 py-6 max-w-full overflow-hidden">
      <PageHeader
        module="INTELLIGENCE FEED V4.2"
        titleKo="이벤트 캘린더"
        titleEn="EVENT CALENDAR"
        description="로봇·AI 글로벌 전시, 학술대회, 정책·규제 이벤트 일정"
      />
      <EventCalendar events={EVENTS} />
    </div>
  );
}

export default function EventCalendarPage() {
  return (
    <AuthGuard>
      <EventCalendarContent />
    </AuthGuard>
  );
}
