/**
 * Actuator catalog · Phase 1 PoC mock data (spec §7.1)
 * ⚠️ 12 entries × 4 vendors. All vendors suffixed with "-Mock".
 */

import type { ActuatorSpec } from '../types.js';

export const ACTUATORS: readonly ActuatorSpec[] = Object.freeze([
  // Tmotor-Mock — quasi-direct drive
  {
    sku: 'TMOTOR-MOCK-AK80-9',
    vendor: 'Tmotor-Mock',
    modelName: 'AK80-9 (mock)',
    type: 'QDD',
    peakTorqueNm: 18,
    continuousTorqueNm: 9,
    maxSpeedRpm: 390,
    weightG: 485,
    diameterMm: 80,
    priceUsdEstimated: 600,
    backdrivable: true,
    isMock: true,
  },
  {
    sku: 'TMOTOR-MOCK-AK10-9',
    vendor: 'Tmotor-Mock',
    modelName: 'AK10-9 (mock)',
    type: 'QDD',
    peakTorqueNm: 48,
    continuousTorqueNm: 18,
    maxSpeedRpm: 297,
    weightG: 960,
    diameterMm: 100,
    priceUsdEstimated: 1100,
    backdrivable: true,
    isMock: true,
  },
  {
    sku: 'TMOTOR-MOCK-AK60-6',
    vendor: 'Tmotor-Mock',
    modelName: 'AK60-6 (mock)',
    type: 'QDD',
    peakTorqueNm: 9,
    continuousTorqueNm: 3,
    maxSpeedRpm: 530,
    weightG: 320,
    diameterMm: 60,
    priceUsdEstimated: 420,
    backdrivable: true,
    isMock: true,
  },
  // Maxon-Mock — BLDC + gearbox
  {
    sku: 'MAXON-MOCK-EC-I-40',
    vendor: 'Maxon-Mock',
    modelName: 'EC-i 40 + GP 42 C (mock)',
    type: 'BLDC+Gearbox',
    peakTorqueNm: 25,
    continuousTorqueNm: 10,
    maxSpeedRpm: 200,
    weightG: 690,
    diameterMm: 42,
    priceUsdEstimated: 1450,
    backdrivable: false,
    isMock: true,
  },
  {
    sku: 'MAXON-MOCK-EC-I-52',
    vendor: 'Maxon-Mock',
    modelName: 'EC-i 52 + GP 52 C (mock)',
    type: 'BLDC+Gearbox',
    peakTorqueNm: 60,
    continuousTorqueNm: 22,
    maxSpeedRpm: 145,
    weightG: 1200,
    diameterMm: 52,
    priceUsdEstimated: 2100,
    backdrivable: false,
    isMock: true,
  },
  {
    sku: 'MAXON-MOCK-EC-FRAMELESS-90',
    vendor: 'Maxon-Mock',
    modelName: 'EC frameless 90 (mock)',
    type: 'BLDC',
    peakTorqueNm: 14,
    continuousTorqueNm: 5,
    maxSpeedRpm: 1500,
    weightG: 380,
    diameterMm: 90,
    priceUsdEstimated: 1100,
    backdrivable: true,
    isMock: true,
  },
  // Unitree-Mock — humanoid/quadruped joint motors
  {
    sku: 'UNITREE-MOCK-B1-HIP',
    vendor: 'Unitree-Mock',
    modelName: 'B1 hip joint (mock)',
    type: 'QDD',
    peakTorqueNm: 80,
    continuousTorqueNm: 30,
    maxSpeedRpm: 240,
    weightG: 1450,
    diameterMm: 110,
    priceUsdEstimated: 1800,
    backdrivable: true,
    isMock: true,
  },
  {
    sku: 'UNITREE-MOCK-B1-KNEE',
    vendor: 'Unitree-Mock',
    modelName: 'B1 knee joint (mock)',
    type: 'QDD',
    peakTorqueNm: 110,
    continuousTorqueNm: 40,
    maxSpeedRpm: 200,
    weightG: 1700,
    diameterMm: 120,
    priceUsdEstimated: 2200,
    backdrivable: true,
    isMock: true,
  },
  {
    sku: 'UNITREE-MOCK-A1-JOINT',
    vendor: 'Unitree-Mock',
    modelName: 'A1 joint (mock)',
    type: 'QDD',
    peakTorqueNm: 33,
    continuousTorqueNm: 14,
    maxSpeedRpm: 320,
    weightG: 605,
    diameterMm: 86,
    priceUsdEstimated: 750,
    backdrivable: true,
    isMock: true,
  },
  // Generic-Mock servos for low-torque needs
  {
    sku: 'GENERIC-MOCK-SERVO-S',
    vendor: 'Generic-Mock',
    modelName: 'Small Servo (mock)',
    type: 'Servo',
    peakTorqueNm: 2.5,
    continuousTorqueNm: 1.5,
    maxSpeedRpm: 60,
    weightG: 70,
    diameterMm: 40,
    priceUsdEstimated: 45,
    backdrivable: false,
    isMock: true,
  },
  {
    sku: 'GENERIC-MOCK-SERVO-M',
    vendor: 'Generic-Mock',
    modelName: 'Medium Servo (mock)',
    type: 'Servo',
    peakTorqueNm: 6,
    continuousTorqueNm: 3,
    maxSpeedRpm: 80,
    weightG: 160,
    diameterMm: 50,
    priceUsdEstimated: 90,
    backdrivable: false,
    isMock: true,
  },
  {
    sku: 'GENERIC-MOCK-SERVO-L',
    vendor: 'Generic-Mock',
    modelName: 'Large Servo (mock)',
    type: 'Servo',
    peakTorqueNm: 18,
    continuousTorqueNm: 8,
    maxSpeedRpm: 60,
    weightG: 350,
    diameterMm: 65,
    priceUsdEstimated: 220,
    backdrivable: false,
    isMock: true,
  },
]);
