/**
 * Sensor catalog · Phase 1 PoC mock data (spec §7.2)
 * ⚠️ Every entry MUST have isMock:true. Vendor names suffixed with "-Mock".
 */

import type { SensorSpec } from '../types.js';

export const SENSORS: readonly SensorSpec[] = Object.freeze([
  {
    sku: 'REALSENSE-MOCK-D435',
    vendor: 'Intel-Mock',
    type: 'RGB-D',
    fovHorizontalDeg: 87,
    fovVerticalDeg: 58,
    rangeMinM: 0.3,
    rangeMaxM: 3.0,
    resolutionPx: '1280x720',
    weightG: 72,
    priceUsdEstimated: 280,
    isMock: true,
  },
  {
    sku: 'REALSENSE-MOCK-D455',
    vendor: 'Intel-Mock',
    type: 'RGB-D',
    fovHorizontalDeg: 87,
    fovVerticalDeg: 58,
    rangeMinM: 0.6,
    rangeMaxM: 6.0,
    resolutionPx: '1280x800',
    weightG: 124,
    priceUsdEstimated: 420,
    isMock: true,
  },
  {
    sku: 'OUSTER-MOCK-OS1',
    vendor: 'Ouster-Mock',
    type: 'LiDAR',
    fovHorizontalDeg: 360,
    fovVerticalDeg: 33,
    rangeMinM: 0.5,
    rangeMaxM: 100,
    resolutionPx: '1024x64',
    weightG: 425,
    priceUsdEstimated: 8500,
    isMock: true,
  },
  {
    sku: 'VELODYNE-MOCK-VLP16',
    vendor: 'Velodyne-Mock',
    type: 'LiDAR',
    fovHorizontalDeg: 360,
    fovVerticalDeg: 30,
    rangeMinM: 1.0,
    rangeMaxM: 100,
    resolutionPx: '1800x16',
    weightG: 830,
    priceUsdEstimated: 4000,
    isMock: true,
  },
  {
    sku: 'TOF-MOCK-IRS2381C',
    vendor: 'Generic-Mock',
    type: 'ToF',
    fovHorizontalDeg: 60,
    fovVerticalDeg: 45,
    rangeMinM: 0.1,
    rangeMaxM: 5.0,
    resolutionPx: '352x288',
    weightG: 18,
    priceUsdEstimated: 95,
    isMock: true,
  },
  {
    sku: 'STEREO-MOCK-ZED2',
    vendor: 'Generic-Mock',
    type: 'Stereo',
    fovHorizontalDeg: 110,
    fovVerticalDeg: 70,
    rangeMinM: 0.3,
    rangeMaxM: 20,
    resolutionPx: '2208x1242',
    weightG: 166,
    priceUsdEstimated: 450,
    isMock: true,
  },
]);
