-- =============================================================
-- ARGOS Competitive Intelligence Data Update — 2026-06-25
-- Auto-generated by scheduled routine
-- =============================================================

BEGIN;

-- ===================== ARTICLES =====================
-- Uses content_hash for deduplication (unique index)
-- ON CONFLICT DO NOTHING to skip existing entries

-- 1. Tesla Optimus: Model S/X line ending, Fremont repurposed for Optimus
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'Tesla Is Turning Its Model S Line Into an Optimus Robot Factory: Gen 3 Targets a 2026 Production Start',
  'TechTimes',
  'https://www.techtimes.com/articles/318071/20260609/tesla-turning-its-model-s-line-optimus-robot-factorygen-3-targets-2026-production-start.htm',
  '2026-06-09'::timestamp,
  'Tesla is ending production of the Model S and Model X, repurposing Fremont factory lines for Optimus humanoid robot production. Gen 3 targets 2026 production start with initial per-unit cost exceeding $60,000.',
  'Tesla plans to begin production of the Optimus Gen 3 robot by end of 2026, repurposing Model S/X lines at Fremont. New Texas facility targets eventual 10M units/year capacity. Q4 2025 earnings acknowledged Optimus is "not in usage in factories in a material way." Per-unit cost still exceeds $60,000.',
  'en', 'industry', 'robot',
  encode(sha256('tesla-optimus-model-s-factory-conversion-2026-06'::bytea), 'hex'),
  '{"mentionedCompanies":["Tesla"],"mentionedRobots":["Optimus","Optimus Gen 3"],"technologies":["humanoid manufacturing","factory conversion"],"keyPoints":["Model S/X production ending","Fremont repurposed for Optimus","Gen 3 targets 2026 production","Per-unit cost >$60K"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Tesla%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 2. Tesla Optimus: Texas Gigafactory expansion for 10M units
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'From EVs to Robotics: Tesla Targets 10M Optimus Units with New Texas Plant',
  'The Robot Report',
  'https://www.therobotreport.com/from-evs-to-robotics-tesla-targets-10m-optimus-units-with-new-texas-plant/',
  '2026-06-01'::timestamp,
  'Tesla broke ground on massive Optimus manufacturing facility at Gigafactory Texas, targeting eventual annual capacity of 10 million units. Scale-up planned by 2027.',
  'Tesla broke ground on a massive new Optimus manufacturing facility at Gigafactory Texas in late 2025, with ambitions to eventually reach 10 million units per year. Production starting 2026, major scale-up by 2027. Initial annual capacity target is 1 million units.',
  'en', 'industry', 'robot',
  encode(sha256('tesla-optimus-texas-10m-units-2026'::bytea), 'hex'),
  '{"mentionedCompanies":["Tesla"],"mentionedRobots":["Optimus"],"technologies":["mass production","factory expansion"],"keyPoints":["Gigafactory Texas expansion","10M units/year target","2027 scale-up plan","1M initial capacity"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Tesla%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 3. Boston Dynamics: Production-ready Atlas at CES 2026
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'Boston Dynamics Launches Production-Ready Atlas at CES 2026',
  'Automate.org',
  'https://www.automate.org/robotics/industry-insights/boston-dynamics-to-begin-production-on-redesigned-atlas-humanoid-in-2026',
  '2026-01-06'::timestamp,
  'Boston Dynamics unveiled production-ready Atlas at CES 2026. All 2026 deployments fully committed to Hyundai RMAC and Google DeepMind. 56 DOF, 4-hour battery, autonomous battery swap capability.',
  'Boston Dynamics unveiled the product version of Atlas at CES 2026. Production began at Boston HQ. Key specs: fully electric, 56 DOF, 110 lbs lift capacity, 7.5 ft reach, 4-hour battery, autonomous self-swappable batteries. All 2026 deployments committed to Hyundai RMAC and Google DeepMind. Hyundai planning dedicated 30,000 unit/year factory by 2028.',
  'en', 'product', 'robot',
  encode(sha256('boston-dynamics-atlas-ces-2026-production'::bytea), 'hex'),
  '{"mentionedCompanies":["Boston Dynamics","Hyundai","Google DeepMind"],"mentionedRobots":["Atlas"],"technologies":["electric actuators","autonomous battery swap","tactile hands"],"keyPoints":["Production-ready at CES 2026","56 DOF","All 2026 deployments committed","Hyundai 30K/year factory by 2028"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Boston Dynamics%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 4. Boston Dynamics: Atlas enters Hyundai factories
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'Atlas Humanoid Robots Enter Hyundai Factories for Industrial Use',
  'New Atlas',
  'https://newatlas.com/ai-humanoids/boston-dynamics-production-atlas-hyundai/',
  '2026-01-10'::timestamp,
  'Atlas robots deployed to Hyundai factories. Google DeepMind provides AI foundation models for faster task learning. Hyundai planning Robotics Metaplant Application Center (RMAC).',
  'Atlas fleets shipping to Hyundai RMAC. Google DeepMind foundation models integrated for cognitive capabilities and faster task learning. More customers expected in 2027.',
  'en', 'industry', 'robot',
  encode(sha256('atlas-hyundai-factories-deployment-2026'::bytea), 'hex'),
  '{"mentionedCompanies":["Boston Dynamics","Hyundai","Google DeepMind"],"mentionedRobots":["Atlas"],"technologies":["foundation models","AI integration"],"keyPoints":["Hyundai factory deployment","Google DeepMind AI partnership","RMAC deployment center"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Boston Dynamics%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 5. Figure AI: Series C exceeds $1B at $39B valuation
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'Figure AI Exceeds $1B in Series C Funding at $39B Post-Money Valuation',
  'Figure AI',
  'https://www.figure.ai/news/series-c',
  '2025-12-01'::timestamp,
  'Figure AI raised over $1B in Series C at $39B valuation. Investors include Brookfield, Intel, NVIDIA, Qualcomm, Salesforce, T-Mobile. Amazon 20K units and Mercedes 50K units orders secured.',
  'Figure AI Series C: >$1B at $39B valuation. Key investors: Brookfield Asset Management, Intel, Macquarie Capital, NVIDIA, Parkway Venture Capital, Qualcomm, Salesforce, T-Mobile. Revenue pipeline: Amazon (20K units) + Mercedes (50K units) = $14B+ through 2029. Figure 02 produced 30K BMW X3 at Spartanburg. Figure 03 introduced Oct 2025. Project Go-Big pretraining via Brookfield 100K residential units.',
  'en', 'industry', 'robot',
  encode(sha256('figure-ai-series-c-1b-39b-valuation-2025'::bytea), 'hex'),
  '{"mentionedCompanies":["Figure AI","Amazon","BMW","Mercedes","Brookfield","NVIDIA","Intel","Qualcomm"],"mentionedRobots":["Figure 02","Figure 03"],"technologies":["Helix 02","motion capture","simulation learning"],"keyPoints":["$1B+ Series C","$39B valuation","20K Amazon + 50K Mercedes orders","$14B revenue pipeline"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Figure%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 6. Figure AI: BMW deployment milestone
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'Figure AI Demonstrates the Future of Humanoid Robotics at BMW Spartanburg Plant',
  'Forge Global',
  'https://forgeglobal.com/insights/figure-ai-robotics-growth-2026/',
  '2026-03-01'::timestamp,
  'After 11-month deployment at BMW Spartanburg, two Figure 02 robots contributed to producing over 30,000 BMW X3 vehicles. Helix 02 AI model enables full-body control.',
  'Figure 02 deployment at BMW Spartanburg (11 months): contributed to 30K+ BMW X3 production. Helix 02 released Jan 2026 for full-body AI control. Figure 02 demonstrated dishwasher loading/unloading, laundry folding, package sorting capabilities.',
  'en', 'technology', 'robot',
  encode(sha256('figure-ai-bmw-spartanburg-30k-x3-2026'::bytea), 'hex'),
  '{"mentionedCompanies":["Figure AI","BMW"],"mentionedRobots":["Figure 02"],"technologies":["Helix 02","full-body AI control","motion capture training"],"keyPoints":["30K BMW X3 produced","11-month deployment","Helix 02 full-body control"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Figure%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 7. Unitree: 20K humanoid target + IPO filing
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'Unitree Targets 20,000 Humanoid Robots with Fourfold Capacity Increase',
  'Interesting Engineering',
  'https://interestingengineering.com/ai-robotics/unitree-targets-20000-humanoid-robots',
  '2026-03-15'::timestamp,
  'Unitree shipped 5,500+ G1 units in 2025 (surpassing combined US competitors), targeting 10K-20K in 2026. IPO filing for Shanghai Stock Exchange at $580M target. 335% YoY revenue growth.',
  'Unitree production: 5,500+ G1 in 2025, targeting 10K-20K in 2026. IPO filing Shanghai Stock Exchange, $580M target, mid-2026 listing. 335% revenue growth YoY. New models: H2, R1, G1-D (wheeled variant). Open-sourced UnifoLM-VLA-0 Vision-Language-Action model for autonomous household tasks.',
  'en', 'industry', 'robot',
  encode(sha256('unitree-20k-target-ipo-2026'::bytea), 'hex'),
  '{"mentionedCompanies":["Unitree"],"mentionedRobots":["G1","H1","H2","R1","G1-D"],"technologies":["UnifoLM-VLA-0","Vision-Language-Action"],"keyPoints":["5,500 shipped 2025","20K target 2026","Shanghai IPO $580M","335% revenue growth"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Unitree%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 8. Agility Robotics: SPAC merger at $2.5B
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'Agility Robotics to Go Public Through $2.5 Billion Merger with Churchill Capital Corp XI',
  'BusinessWire',
  'https://www.businesswire.com/news/home/20260624555633/en/Agility-Robotics-to-Go-Public-Through-$2.5-Billion-Merger-with-Churchill-Capital-Corp-XI',
  '2026-06-24'::timestamp,
  'Agility Robotics going public via SPAC at $2.5B valuation with $620M+ proceeds. $300M+ multi-year Digit v5 orders. 65,000+ operational hours across 9 facilities. NVIDIA Halos launch partner.',
  'Agility SPAC merger with Churchill Capital Corp XI at $2.5B, $620M+ gross proceeds. Digit v5: 50 lb lift (40% increase), 22-hour operation, 7.2 ft reach. $300M+ multi-year orders. 65,000+ operational hours. Customers: Schaeffler, GXO, Toyota Motor Canada, Mercado Libre. Partners: NVIDIA (Halos), Google DeepMind, Amazon, SoftBank, Foxconn.',
  'en', 'industry', 'robot',
  encode(sha256('agility-spac-2.5b-churchill-2026-06'::bytea), 'hex'),
  '{"mentionedCompanies":["Agility Robotics","Churchill Capital","NVIDIA","Google DeepMind","Amazon","Schaeffler","GXO","Toyota","Mercado Libre"],"mentionedRobots":["Digit","Digit v5"],"technologies":["NVIDIA Halos","cooperative safety"],"keyPoints":["$2.5B SPAC merger","$300M+ orders","65K operational hours","NVIDIA Halos launch partner"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Agility%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 9. Apptronik: $520M funding at $5B valuation
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'Apptronik Raises $520 Million at $5 Billion Valuation for Apollo Robot',
  'CNBC',
  'https://www.cnbc.com/2026/02/11/apptronik-raises-520-million-at-5-billion-valuation-for-apollo-robot.html',
  '2026-02-11'::timestamp,
  'Apptronik closed $520M Series A-X at ~$5B valuation, bringing total funding to ~$1B. New investors: AT&T Ventures, John Deere, QIA. Google DeepMind Gemini models partnership.',
  'Apptronik $520M Series A-X extension at ~$5B valuation. Total Series A >$935M, overall funding ~$1B. Returning: Google, Mercedes-Benz, B Capital. New: AT&T Ventures, John Deere, Qatar Investment Authority. Apollo: 25 kg payload, 71 DOF. Active at Mercedes factories and GXO warehouses. Google DeepMind Gemini Robotics AI models integration. Next-gen platform planned later 2026.',
  'en', 'industry', 'robot',
  encode(sha256('apptronik-520m-5b-valuation-2026-02'::bytea), 'hex'),
  '{"mentionedCompanies":["Apptronik","Google","Mercedes-Benz","AT&T","John Deere","QIA","Google DeepMind"],"mentionedRobots":["Apollo"],"technologies":["Gemini Robotics","25kg payload","71 DOF"],"keyPoints":["$520M Series A-X","$5B valuation","~$1B total funding","Google DeepMind Gemini partnership"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Apptronik%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 10. 1X Technologies: NEO factory + 10K production
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  '1X Technologies Opens First US Humanoid Factory, Targets 100,000 Robots by 2027',
  'TechFundingNews',
  'https://techfundingnews.com/openai-backed-1x-first-us-humanoid-factory-sold-out-production/',
  '2026-04-01'::timestamp,
  '1X opened 58K sqft Hayward CA factory — first vertically integrated US humanoid factory. 10K first-year capacity sold out in 5 days. NEO priced at $20K or $499/month. EQT deal for 10K units 2026-2030.',
  '1X Technologies Hayward CA factory: 58K sqft, first vertically integrated US humanoid manufacturing. 10K unit first-year capacity, sold out in 5 days. NEO Gamma: 5ft 7in, 66 lbs, bipedal, soft 3D-knit exterior, five-fingered hands. Price: $20K purchase or $499/month rental. EQT deal: up to 10K units 2026-2030 for 300+ portfolio companies. Target: 100K units by end 2027.',
  'en', 'industry', 'robot',
  encode(sha256('1x-neo-hayward-factory-10k-2026'::bytea), 'hex'),
  '{"mentionedCompanies":["1X Technologies","EQT","OpenAI"],"mentionedRobots":["NEO","NEO Gamma"],"technologies":["vertically integrated manufacturing","3D-knit exterior","bipedal locomotion"],"keyPoints":["Hayward CA factory opened","10K capacity sold out in 5 days","$20K price point","EQT 10K unit deal"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%1X%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;

-- 11. Agibot: 10,000th unit + Partner Conference
INSERT INTO articles (id, company_id, title, source, url, published_at, summary, content, language, category, product_type, content_hash, extracted_metadata, collected_at)
SELECT gen_random_uuid(), c.id,
  'AgiBot Hits 10,000 Units: China Humanoid Robot Duopoly Takes Shape',
  'TechTimes',
  'https://www.techtimes.com/articles/317632/20260602/unitree-ipo-cleared-agibot-hits-10000-units-china-humanoid-robot-duopoly-takes-shape.htm',
  '2026-06-02'::timestamp,
  'AgiBot produced 10,000th humanoid on March 30, 2026. Launched 5 new platforms + 8 AI models. Partnerships with Minth Group (Europe) and Singtel (Singapore). Unitree+AgiBot projected ~80% China market.',
  'AgiBot 10,000th humanoid produced March 30, 2026. Fourfold throughput acceleration via supply chain standardization. 2026 Partner Conference: 5 new robot platforms, 8 AI models, "One Robotic Body, Three Intelligences" architecture. X1 fully open-source. Partnerships: Minth Group (European auto parts), Singtel Enterprise (Singapore). Hong Kong IPO planned Q3 2026. Unitree + AgiBot projected ~80% China humanoid market share (TrendForce).',
  'en', 'industry', 'robot',
  encode(sha256('agibot-10000-units-duopoly-2026-06'::bytea), 'hex'),
  '{"mentionedCompanies":["AgiBot","Unitree","Minth Group","Singtel"],"mentionedRobots":["X1","Lingxi X1"],"technologies":["open-source platform","embodied AI","One Body Three Intelligences"],"keyPoints":["10,000th unit produced","5 new platforms + 8 AI models","Minth + Singtel partnerships","Hong Kong IPO Q3 2026"]}'::jsonb,
  NOW()
FROM companies c WHERE c.name ILIKE '%Agibot%' OR c.name ILIKE '%AgiBot%' LIMIT 1
ON CONFLICT (content_hash) DO NOTHING;


-- ===================== COMPETITIVE ALERTS =====================

-- Alert 1: Agility Robotics SPAC — critical partnership/funding
INSERT INTO competitive_alerts (id, robot_id, type, severity, title, summary, trigger_data, is_read, created_at)
SELECT gen_random_uuid(),
  r.id,
  'funding', 'critical',
  'Agility Robotics SPAC 합병으로 상장 — $2.5B 기업가치',
  'Agility Robotics가 Churchill Capital Corp XI과 SPAC 합병을 통해 $2.5B 기업가치로 상장 예정. $620M 이상의 자금 조달. Digit v5에 대한 $300M+ 다년간 주문 확보. NVIDIA Halos 출시 파트너로 선정.',
  '{"source":"BusinessWire","date":"2026-06-24","valuation":"$2.5B","proceeds":"$620M+","orders":"$300M+","confidence":"A"}'::jsonb,
  false, NOW()
FROM humanoid_robots r WHERE r.name ILIKE '%Digit%' LIMIT 1
ON CONFLICT DO NOTHING;

-- Alert 2: Boston Dynamics Atlas production shipments begin
INSERT INTO competitive_alerts (id, robot_id, type, severity, title, summary, trigger_data, is_read, created_at)
SELECT gen_random_uuid(),
  r.id,
  'mass_production', 'critical',
  'Boston Dynamics Atlas 양산 시작 — CES 2026 공개, 현대 공장 배치',
  'Boston Dynamics가 CES 2026에서 양산형 Atlas를 공개하고 즉시 생산 시작. 2026년 전체 배치 물량 이미 확약. 현대 RMAC 및 Google DeepMind에 우선 공급. 현대는 2028년까지 연 30,000대 규모 전용 공장 계획.',
  '{"source":"Automate.org / NewAtlas","date":"2026-01-06","deployments":"fully committed 2026","hyundaiFactory":"30K/year by 2028","confidence":"A"}'::jsonb,
  false, NOW()
FROM humanoid_robots r WHERE r.name ILIKE '%Atlas%' LIMIT 1
ON CONFLICT DO NOTHING;

-- Alert 3: Apptronik $520M funding
INSERT INTO competitive_alerts (id, robot_id, type, severity, title, summary, trigger_data, is_read, created_at)
SELECT gen_random_uuid(),
  r.id,
  'funding', 'warning',
  'Apptronik $520M 추가 투자 유치 — $5B 기업가치, Google DeepMind 제휴',
  'Apptronik이 Series A-X에서 $520M을 추가 조달하여 총 ~$1B 투자 유치. 기업가치 ~$5B. AT&T Ventures, John Deere, 카타르투자청(QIA) 신규 참여. Google DeepMind Gemini 모델 통합.',
  '{"source":"CNBC","date":"2026-02-11","amount":"$520M","valuation":"$5B","totalFunding":"~$1B","newInvestors":["AT&T Ventures","John Deere","QIA"],"confidence":"A"}'::jsonb,
  false, NOW()
FROM humanoid_robots r WHERE r.name ILIKE '%Apollo%' LIMIT 1
ON CONFLICT DO NOTHING;

-- Alert 4: Figure AI massive order pipeline
INSERT INTO competitive_alerts (id, robot_id, type, severity, title, summary, trigger_data, is_read, created_at)
SELECT gen_random_uuid(),
  r.id,
  'partnership', 'critical',
  'Figure AI: Amazon 2만대 + Mercedes 5만대 주문 — $14B 매출 파이프라인',
  'Figure AI가 Amazon(20K대)과 Mercedes(50K대)로부터 대규모 주문을 확보, 2029년까지 $14B+ 매출 파이프라인 구축. Series C에서 $1B+ 조달($39B 기업가치). BMW 스파르탄버그 공장에서 11개월간 Figure 02 실전 배치.',
  '{"source":"Figure AI / Forge Global","date":"2026-03","orders":{"amazon":"20K units","mercedes":"50K units"},"revenuePipeline":"$14B+","valuation":"$39B","confidence":"A"}'::jsonb,
  false, NOW()
FROM humanoid_robots r WHERE r.name ILIKE '%Figure 0%' LIMIT 1
ON CONFLICT DO NOTHING;

-- Alert 5: AgiBot 10K units — China duopoly
INSERT INTO competitive_alerts (id, robot_id, type, severity, title, summary, trigger_data, is_read, created_at)
SELECT gen_random_uuid(),
  r.id,
  'mass_production', 'warning',
  'AgiBot 누적 10,000대 생산 돌파 — 중국 휴머노이드 시장 양강 구도',
  'AgiBot가 2026년 3월 30일 10,000번째 휴머노이드 생산. Unitree와 함께 중국 휴머노이드 시장의 약 80% 점유 전망(TrendForce). Minth Group(유럽)·Singtel(싱가포르) 등 해외 파트너십 확대. 홍콩 IPO Q3 2026 예정.',
  '{"source":"TechTimes / TrendForce","date":"2026-06-02","productionMilestone":"10,000 units","marketShare":"~80% with Unitree","ipoTarget":"Hong Kong Q3 2026","confidence":"B"}'::jsonb,
  false, NOW()
FROM humanoid_robots r WHERE r.name ILIKE '%X1%' OR r.name ILIKE '%Agibot%' LIMIT 1
ON CONFLICT DO NOTHING;

-- Alert 6: Unitree IPO + production scale
INSERT INTO competitive_alerts (id, robot_id, type, severity, title, summary, trigger_data, is_read, created_at)
SELECT gen_random_uuid(),
  r.id,
  'funding', 'warning',
  'Unitree 상하이 IPO 추진 — 2025년 5,500대 출하, 2026년 20K 목표',
  'Unitree가 상하이증권거래소 A주 상장을 추진 중($580M 목표). 2025년 G1 5,500대+ 출하로 미국 경쟁사 합산 초과. 2026년 10K-20K대 목표. 전년대비 335% 매출 성장.',
  '{"source":"eWeek / Interesting Engineering","date":"2026-03","shipped2025":"5,500+","target2026":"10K-20K","ipoTarget":"$580M Shanghai","revenueGrowth":"335%","confidence":"B"}'::jsonb,
  false, NOW()
FROM humanoid_robots r WHERE r.name ILIKE '%G1%' OR r.name ILIKE '%H1%' LIMIT 1
ON CONFLICT DO NOTHING;

-- Alert 7: 1X Technologies NEO sold out
INSERT INTO competitive_alerts (id, robot_id, type, severity, title, summary, trigger_data, is_read, created_at)
SELECT gen_random_uuid(),
  r.id,
  'mass_production', 'info',
  '1X Technologies NEO 첫해 생산분 10K대 5일만에 완판',
  '1X Technologies가 미국 헤이워드에 58K sqft 규모 최초 수직통합 휴머노이드 공장 개설. 첫해 10K대 생산 용량이 사전주문 개시 5일만에 완판. $20K 판매 또는 $499/월 렌탈. EQT 10K대 딜(2026-2030).',
  '{"source":"TechFundingNews / TNW","date":"2026-04","factory":"58K sqft Hayward CA","capacity":"10K first year","soldOutIn":"5 days","price":"$20K or $499/mo","confidence":"B"}'::jsonb,
  false, NOW()
FROM humanoid_robots r WHERE r.name ILIKE '%NEO%' LIMIT 1
ON CONFLICT DO NOTHING;

-- Alert 8: Tesla Optimus factory conversion
INSERT INTO competitive_alerts (id, robot_id, type, severity, title, summary, trigger_data, is_read, created_at)
SELECT gen_random_uuid(),
  r.id,
  'mass_production', 'warning',
  'Tesla Optimus Gen 3 생산 개시 임박 — Model S 라인 전환, 연 10M대 목표',
  'Tesla가 Fremont 공장 Model S/X 라인을 Optimus 생산라인으로 전환. 텍사스 기가팩토리에 대규모 Optimus 제조시설 착공. 2026년 Gen 3 양산 시작 목표, 최종적으로 연 1,000만대 생산 계획. 현재 초기 대당 비용 $60K+.',
  '{"source":"TechTimes / Robot Report","date":"2026-06","factoryConversion":"Fremont Model S/X -> Optimus","texasExpansion":"new facility","unitCost":">$60K","target":"10M/year eventually","confidence":"B"}'::jsonb,
  false, NOW()
FROM humanoid_robots r WHERE r.name ILIKE '%Optimus%' LIMIT 1
ON CONFLICT DO NOTHING;

COMMIT;
