'use client';

import Link from 'next/link';
import { EmptyChartPlaceholder } from '../shared/EmptyChartPlaceholder';

interface BriefReport {
  id: string;
  title: string;
  pageCount: number;
  updatedAt: string;
  isAutoGenerated: boolean;
}

interface NewsEvent {
  id: string;
  date: string;
  type: 'investment' | 'poc' | 'production' | 'other';
  title: string;
  comment?: string;
  url?: string;
}

interface InsightHubPanelProps {
  latestReport?: BriefReport;
  topNews: NewsEvent[];
  isLoading?: boolean;
  onViewReport?: () => void;
  onExportPPT?: () => void;
}

const eventTypeIcons: Record<string, { icon: string; color: string; label: string }> = {
  investment: { icon: '💰', color: 'text-green-400', label: '투자' },
  poc: { icon: '🔬', color: 'text-yellow-400', label: 'PoC' },
  production: { icon: '🏭', color: 'text-purple-400', label: '양산' },
  other: { icon: '📰', color: 'text-slate-400', label: '기타' },
};

export function InsightHubPanel({
  latestReport,
  topNews,
  isLoading = false,
  onViewReport,
  onExportPPT,
}: InsightHubPanelProps) {
  if (isLoading) {
    return (
      <div className="bg-slate-900 rounded-xl p-6 h-full animate-pulse">
        <div className="h-6 bg-slate-700 rounded w-1/2 mb-4" />
        <div className="h-24 bg-slate-800 rounded mb-4" />
        <div className="space-y-3">
          {Array.from({ length: 5 }).map((_, i) => (
            <div key={i} className="h-12 bg-slate-800 rounded" />
          ))}
        </div>
      </div>
    );
  }

  if (!latestReport && topNews.length === 0) {
    return (
      <div className="bg-slate-900 rounded-xl p-6 h-full">
        <EmptyChartPlaceholder
          title="인사이트 데이터 없음"
          message="인사이트 데이터가 없습니다"
          icon="📋"
          dataType="기사"
          minDataCount={1}
        />
      </div>
    );
  }

  return (
    <div className="bg-slate-900 rounded-xl p-6 h-full flex flex-col">
      {/* Header */}
      <h3 className="text-lg font-semibold text-white flex items-center gap-2 mb-4">
        <span className="text-xl">📋</span>
        리포트 & 뉴스 허브
      </h3>

      {/* Latest Brief Report */}
      {latestReport && (
        <div className="bg-gradient-to-br from-blue-900/40 to-blue-800/20 border border-blue-700/30 rounded-lg p-4 mb-4">
          <div className="flex items-start justify-between mb-2">
            <h4 className="text-sm font-medium text-white line-clamp-2">{latestReport.title}</h4>
            {latestReport.isAutoGenerated && (
              <span className="text-xs bg-blue-600/30 text-blue-300 px-2 py-0.5 rounded shrink-0 ml-2">
                AI 생성
              </span>
            )}
          </div>
          <div className="flex items-center gap-2 text-xs text-slate-400 mb-3">
            <span>{latestReport.pageCount}페이지</span>
            <span>•</span>
            <span>업데이트: {latestReport.updatedAt}</span>
          </div>
          <div className="flex gap-2">
            <button
              onClick={onViewReport}
              className="flex-1 px-3 py-1.5 text-xs bg-slate-700 hover:bg-slate-600 text-white rounded-md transition-colors"
            >
              요약 보기
            </button>
            <button
              onClick={onExportPPT}
              className="flex-1 px-3 py-1.5 text-xs bg-blue-600 hover:bg-blue-500 text-white rounded-md transition-colors"
            >
              PPT 내보내기
            </button>
          </div>
        </div>
      )}

      {/* Top 5 News & Events */}
      <div className="flex-1 overflow-hidden">
        <h4 className="text-sm font-medium text-slate-400 mb-3">Top 5 뉴스 & 이벤트</h4>
        <div className="space-y-2 overflow-y-auto max-h-[calc(100%-2rem)]">
          {topNews.length > 0 ? (
            topNews.slice(0, 5).map((news) => {
              const typeInfo = eventTypeIcons[news.type] || eventTypeIcons.other;
              return (
                <div
                  key={news.id}
                  className="bg-slate-800/50 hover:bg-slate-800 rounded-lg p-3 cursor-pointer transition-colors"
                  onClick={() => news.url && window.open(news.url, '_blank')}
                >
                  <div className="flex items-start gap-2">
                    <span className="text-lg shrink-0">{typeInfo.icon}</span>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-xs text-slate-500">{news.date}</span>
                        <span className={`text-xs ${typeInfo.color}`}>{typeInfo.label}</span>
                      </div>
                      <p className="text-sm text-white line-clamp-1">{news.title}</p>
                      {news.comment && (
                        <p className="text-xs text-slate-400 mt-1 line-clamp-1">
                          💬 {news.comment}
                        </p>
                      )}
                    </div>
                  </div>
                </div>
              );
            })
          ) : (
            <p className="text-sm text-slate-500 text-center py-4">뉴스가 없습니다</p>
          )}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="mt-4 pt-4 border-t border-slate-800">
        <h4 className="text-xs font-medium text-slate-500 mb-2">자주 쓰는 작업</h4>
        <div className="grid grid-cols-3 gap-2">
          <Link
            href="/humanoid-robots"
            className="flex flex-col items-center gap-1 p-2 bg-slate-800/50 hover:bg-slate-800 rounded-lg transition-colors"
          >
            <span className="text-lg">🤖</span>
            <span className="text-xs text-slate-400">카탈로그</span>
          </Link>
          <Link
            href="/companies"
            className="flex flex-col items-center gap-1 p-2 bg-slate-800/50 hover:bg-slate-800 rounded-lg transition-colors"
          >
            <span className="text-lg">🏆</span>
            <span className="text-xs text-slate-400">회사 랭킹</span>
          </Link>
          <Link
            href="/ppt-builder"
            className="flex flex-col items-center gap-1 p-2 bg-slate-800/50 hover:bg-slate-800 rounded-lg transition-colors"
          >
            <span className="text-lg">📊</span>
            <span className="text-xs text-slate-400">PPT 생성</span>
          </Link>
        </div>
      </div>
    </div>
  );
}
